config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get "restaurants", to: "restaurants#index"
  # get "restaurants/:id", to: "restaurants#show", as: :restaurant

  # get "restaurants/new", to: "restaurants#new"
  # post "restaurants", to: "restaurants#create"
  # get "restaurants", to: "restaurants#index"
  # get "/restaurants/:restaurant_id/reviews" to: "review#index"

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants, only: %i[index new create show] do
    resources :reviews, only: %i[index new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def index
    set_restaurant
    @reviews = Review.where(restaurant_id: @restaurant)
  end

  # def new
  #   @review = Review.new
  # end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show', status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating, :restaurant_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name, placeholder: "Restaurant"%>
  <%= f.input :address,  placeholder: "Address" %>
  <%= f.input :phone_number, placeholder: "Phone number" %>
  <%= f.input :category, placeholder: "Type of restaurant" %>
  <%= f.submit "Add", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants:</h1>
<hr>

<div class="container">
<ul>
  <% @restaurants.each do |restaurant| %>
    <li> <%= link_to restaurant.name, restaurant_path(restaurant.id), class: "link"%></li>
  <% end %>
</ul>

</div>

<hr>

<%= link_to new_restaurant_path do %>
  <i class="fa fa-plus">Add a new restaurant</i>
<% end %>

app/views/restaurants/new.html.erb
<h1>Add a new restaurant:</h1>
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1>Restaurant details</h1>
<hr>
<div class = "container">
  <h2><%= @restaurant.name %></h2>
  <p><%= @restaurant.address %></p>
  <p><%= @restaurant.phone_number %></p>
  <p><%= @restaurant.category %></p>
</div>
  <%# <%= link_to 'Reviews', restaurant_reviews_path(@restaurant) %>
  <hr>
<ul class="list-group">
  <p>Reviews</p>
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item"><%= review.content %><%= review.rating %></li>
  <% end %>
</ul>
<br>
  <%# <%= link_to 'Add a new review', new_restaurant_review_path(@restaurant.id)%>
  <p>Add a new review:</p>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content, placeholder: "Type here..."%>
    <%= f.input :rating,  placeholder: "Add a rating (1-5)" %>
    <%= f.submit "Add your review", class: "btn btn-primary" %>
<% end %>
<br>
<%= link_to "Back to restaurants", restaurants_path(@restaurants) %>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content, placeholder: "Type here..."%>
  <%= f.input :rating,  placeholder: "Add a rating (1-5)" %>
  <%= f.submit "Add your review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/index.html.erb
<h2>Reviews:</h2>
<hr>
<ul class="list-group">
  <% @reviews.each do |review| %>
    <li class="list-group-item"><%= review.content %><%= review.rating %></li>
  <% end %>
</ul>
<br>


<%= link_to 'Back to Restaurant', restaurants_path %>